### ISSUE TITLE
encountered an error while using the aftermath-ts-sdk in my React TypeScript project

### ISSUE THREAD

**Issue by qxyanda** [AftermathFinance/aftermath-ts-sdk#89]
code:
```
import { Aftermath } from 'aftermath-ts-sdk'

const afSdk = new Aftermath("MAINNET"); // "MAINNET" | "TESTNET" | "DEVNET"
await afSdk.init(); // initialize provider
```

error:
```
DevTools failed to load source map: Could not load content for chrome-extension://opcgpfmipidbgpenhmajoajpbobppdil/content-script.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://opcgpfmipidbgpenhmajoajpbobppdil/dapp-interface.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
chunk-OL46QLBJ.js?v=dc914cfd:21 Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools
util.js:109 Uncaught ReferenceError: process is not defined
    at node_modules/util/util.js (util.js:109:1)
    at __require2 (chunk-OL46QLBJ.js?v=dc914cfd:21:50)
    at node_modules/assert/build/internal/assert/assertion_error.js (assertion_error.js:25:16)
    at __require2 (chunk-OL46QLBJ.js?v=dc914cfd:21:50)
    at node_modules/assert/build/assert.js (assert.js:39:22)
    at __require2 (chunk-OL46QLBJ.js?v=dc914cfd:21:50)
    at node_modules/@scallop-io/sui-scallop-sdk/dist/index.js (sCoinQuery.ts:2:20)
    at __require2 (chunk-OL46QLBJ.js?v=dc914cfd:21:50)
    at node_modules/aftermath-ts-sdk/dist/general/utils/helpers.js (helpers.js:20:27)
    at __require2 (chunk-OL46QLBJ.js?v=dc914cfd:21:50)
node_modules/util/util.js @ util.js:109
__require2 @ chunk-OL46QLBJ.js?v=dc914cfd:21
node_modules/assert/build/internal/assert/assertion_error.js @ assertion_error.js:25
__require2 @ chunk-OL46QLBJ.js?v=dc914cfd:21
node_modules/assert/build/assert.js @ assert.js:39
__require2 @ chunk-OL46QLBJ.js?v=dc914cfd:21
node_modules/@scallop-io/sui-scallop-sdk/dist/index.js @ sCoinQuery.ts:2
__require2 @ chunk-OL46QLBJ.js?v=dc914cfd:21
node_modules/aftermath-ts-sdk/dist/general/utils/helpers.js @ helpers.js:20
__require2 @ chunk-OL46QLBJ.js?v=dc914cfd:21
node_modules/aftermath-ts-sdk/dist/general/utils/caller.js @ caller.js:14
__require2 @ chunk-OL46QLBJ.js?v=dc914cfd:21
node_modules/aftermath-ts-sdk/dist/packages/coin/coin.js @ coin.js:13
__require2 @ chunk-OL46QLBJ.js?v=dc914cfd:21
node_modules/aftermath-ts-sdk/dist/packages/coin/index.js @ index.js:17
__require2 @ chunk-OL46QLBJ.js?v=dc914cfd:21
node_modules/aftermath-ts-sdk/dist/packages/nftAmm/api/nftAmmApiCasting.js @ nftAmmApiCasting.js:5
__require2 @ chunk-OL46QLBJ.js?v=dc914cfd:21
node_modules/aftermath-ts-sdk/dist/general/utils/casting.js @ casting.js:8
__require2 @ chunk-OL46QLBJ.js?v=dc914cfd:21
node_modules/aftermath-ts-sdk/dist/general/utils/index.js @ index.js:17
__require2 @ chunk-OL46QLBJ.js?v=dc914cfd:21
node_modules/aftermath-ts-sdk/dist/packages/pools/utils/cmmmCalculations.js @ cmmmCalculations.js:5
__require2 @ chunk-OL46QLBJ.js?v=dc914cfd:21
node_modules/aftermath-ts-sdk/dist/packages/pools/pool.js @ pool.js:13
__require2 @ chunk-OL46QLBJ.js?v=dc914cfd:21
node_modules/aftermath-ts-sdk/dist/packages/pools/pools.js @ pools.js:14
__require2 @ chunk-OL46QLBJ.js?v=dc914cfd:21
node_modules/aftermath-ts-sdk/dist/general/providers/aftermath.js @ aftermath.js:13
__require2 @ chunk-OL46QLBJ.js?v=dc914cfd:21
node_modules/aftermath-ts-sdk/dist/general/providers/index.js @ index.js:17
__require2 @ chunk-OL46QLBJ.js?v=dc914cfd:21
node_modules/aftermath-ts-sdk/dist/index.js @ index.js:17
__require2 @ chunk-OL46QLBJ.js?v=dc914cfd:21
(anonymous) @ index.js:20

```

**Comment by AguaPotavel** [comment]
the sdk don't work on client side, i forked the repo and fixed to work on client side if you want to use 

https://github.com/AguaPotavel/client-aftermath-ts-sdk
